# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20170509_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
