# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='label',
            field=models.CharField(default='Unnamed Draft - 2017-05-09 03:53:17.012023', max_length=100),
        ),
    ]
